---
- hosts: all
  become: yes
  tasks:
    - name: create the 'kubeuser' user
      user: name=kubeuser append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'kubeuser' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'kubeuser ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the ubuntu user
      authorized_key: user=kubeuser key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub